[package]
name = "rl_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.18"
rl_core = { path = "../rl_core" }
rl_math = { path = "../rl_math" }
